
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class data_capres extends javax.swing.JFrame {
String ft;
String aa;
    /**
     * Creates new form data_panitia
     */
    public data_capres() {
        initComponents();
        lihatdata();
        setLocationRelativeTo(null);
        setTitle("Data Capres");
        combo_no_urut();
    }
    public void lihatdata(){
         DefaultTableModel ea = new DefaultTableModel();
        ea.addColumn("Id Capres");
        ea.addColumn("Nama Capres");
        ea.addColumn("Jenis Kelamin");
        ea.addColumn("Alamat");
        ea.addColumn("No Urut");
        ea.addColumn("Foto");
        
        try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
            String sql = "Select * from capres";
            ResultSet res = perintah.executeQuery(sql);
            while(res.next()){
                ea.addRow(new Object []{
                    
                    res.getString("id_capres"),
                    res.getString("nama_capres"),
                    res.getString("jenis_kelamin"),
                    res.getString("alamat"),
                    res.getString("no_urut"),
                    res.getString("foto")
                });
            }
            tabel.setModel(ea);
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, "Error"+err);
            
        }
        
    }
    
    public void combo_no_urut(){
         
        no_urut.removeAllItems();
        
        try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
            String sql = "Select * from hasil_suara";
            ResultSet res = perintah.executeQuery(sql);
            while(res.next()){
                no_urut.addItem(res.getString("no_urut"));
            }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err);
     
    }
    }
    
    public void bersih(){
        id_capres.setText("");
        nama_capres.setText("");
        
        jk.clearSelection();
        alamat.setText("");
        foto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jk = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        id_capres = new javax.swing.JTextField();
        laki_laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        foto = new javax.swing.JTextField();
        browser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cetak_semua = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        textcari = new javax.swing.JTextField();
        lihat = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        no_urut = new javax.swing.JComboBox<>();
        nama_capres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new
            javax.swing.ImageIcon(getClass().getResource("/user.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Id Carpes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Nama Capres");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("No Urut");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Foto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1020, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("DATA CAPRES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 20));

        id_capres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(id_capres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 300, -1));

        jk.add(laki_laki);
        laki_laki.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        laki_laki.setText("Laki - Laki");
        getContentPane().add(laki_laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, -1));

        jk.add(perempuan);
        perempuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        perempuan.setText("Perempuan");
        getContentPane().add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 300, -1));

        foto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 180, -1));

        browser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        browser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data.png"))); // NOI18N
        browser.setText("Browser");
        browser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browserActionPerformed(evt);
            }
        });
        getContentPane().add(browser, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 110, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 710, 110));

        simpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b_save.png"))); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 100, 60));

        edit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b_edit.png"))); // NOI18N
        edit.setText("Ubah");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 100, 60));

        hapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b_drop.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 100, 60));

        cetak_semua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cetak_semua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        cetak_semua.setText("Cetak Semua");
        cetak_semua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak_semuaActionPerformed(evt);
            }
        });
        getContentPane().add(cetak_semua, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 170, 140));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polos.png"))); // NOI18N
        jButton3.setText("Cetak Parameter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 170, 60));

        textcari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(textcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 100, -1));

        lihat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lihat.setText("Lihat Data");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        getContentPane().add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        cari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 70, -1));

        no_urut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        no_urut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(no_urut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 300, -1));

        nama_capres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(nama_capres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String isi = "";
        if(laki_laki.isSelected()){
            isi = laki_laki.getText();
        }else{
            isi = perempuan.getText();
        }
        try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
            String sql = "Insert into capres values ('"+id_capres.getText()+"','"+nama_capres.getText()+"','"+isi.toString()+"','"+alamat.getText()+"','"+no_urut.getSelectedItem()+"','"+ft+"')";
            perintah.executeUpdate(sql);
             Path lama = Paths.get(foto.getText());
Path baru = Paths.get("foto\\capres\\"+ft);            
           try{
Files.copy(lama,baru);
}catch(Exception kh){
    JOptionPane.showMessageDialog(null,"maaf tidak jadi jadi :V"+kh);
}
            perintah.close();
            lihatdata();
            bersih();
            
            JOptionPane.showMessageDialog(null,"Data Berhasil Di Tambahkan");
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err );
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void browserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browserActionPerformed
                JFileChooser chooser = new JFileChooser();
       
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                
                "JPG, GIF, and PNG Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
             foto.setText(chooser.getSelectedFile().toString());
            ft=chooser.getSelectedFile().getName().toString();
    

    }//GEN-LAST:event_browserActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
            String isi = "";
            if (laki_laki.isSelected()){
                isi = laki_laki.getText();
            }else{
                perempuan.getText();
            }
        try{
            Statement perintah = (Statement)koneksi.GetConnection().createStatement();
            String sql = "Update capres set nama_capres = '"+nama_capres.getText()+"',jenis_kelamin = '"+isi.toString()+"',alamat = '"+alamat.getText()+"',no_urut = '"+no_urut.getSelectedItem()+"',foto = '"+ft+"'  where id_capres = '"+id_capres.getText()+"'";
            perintah.executeUpdate(sql);
                        Path lama = Paths.get(foto.getText());
                Path baru = Paths.get("foto\\capres\\"+ft); 
            try{
                Files.copy(lama,baru);
            }catch(Exception wa){
                JOptionPane.showMessageDialog(null,"Error"+wa);
            }
            try{
                Path ae = Paths.get("foto\\capres\\"+aa);
                Files.delete(ae);
            }catch(Exception exa){
                JOptionPane.showMessageDialog(null, "Error"+exa);
            }
           perintah.close();
           lihatdata();
           bersih();
        
            JOptionPane.showMessageDialog(null,"Data Berhasil Di Edit");
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err);
        }
        
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
          try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
            String sql = "delete from capres where id_capres = '"+id_capres.getText()+"'";
            perintah.executeUpdate(sql);
                                try{
    Path aa=Paths.get("foto\\capres\\"+ft);
    Files.delete(aa);
    }catch(Exception as){
       JOptionPane.showMessageDialog(null,"delete gagal"+as);
    }     
            perintah.close();
            lihatdata();
            bersih();
        
            JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err);
        }        
    }//GEN-LAST:event_hapusActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
                int table = tabel.getSelectedRow();
        
        String a = tabel.getValueAt(table,0).toString();
        String b = tabel.getValueAt(table,1).toString();
        String c = tabel.getValueAt(table,2).toString();
        String d = tabel.getValueAt(table,3).toString();
        String e = tabel.getValueAt(table,4).toString();
        String f = tabel.getValueAt(table,5).toString();
        
        id_capres.setText(a);
        nama_capres.setText(b);
            if ("Laki - Laki".equals(tabel.getValueAt(table, 2).toString())) {
laki_laki.setSelected(true);
} else {
perempuan.setSelected(true);
}
        alamat.setText(d);
        no_urut.setSelectedItem(e);
        foto.setText(f);
        ft = f;
        aa = f;
        
        id_capres.setEnabled(true);
        nama_capres.requestFocus();
        simpan.setEnabled(true);

    }//GEN-LAST:event_tabelMouseClicked

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        lihatdata();
    }//GEN-LAST:event_lihatActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
                 DefaultTableModel Tabelcoy = new DefaultTableModel();
     Tabelcoy.addColumn("Id Capres");
     Tabelcoy.addColumn("Nama Capres");
     Tabelcoy.addColumn("Jenis Kelamin");
     Tabelcoy.addColumn("Alamat");
     Tabelcoy.addColumn("No Urut");
     Tabelcoy.addColumn("Foto");
     String cari = textcari.getText();
         try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
          String sql = "Select * From capres Where id_capres LIKE '%"+cari+"%'"
                    + "OR nama_capres LIKE '%"+cari+"%' OR jenis_kelamin LIKE '%"+cari+"%'"
                    + "OR alamat LIKE '%"+cari+"%' OR no_urut LIKE '%"+cari+"%'"
                    + "OR foto LIKE '%"+cari+"%' ORDER BY id_capres";
            ResultSet res = perintah.executeQuery(sql);
          while(res.next()){
                Tabelcoy.addRow(new Object[]{
                res.getString(1),
                res.getString(2),
                res.getString(3),
                res.getString(4),
                res.getString(5),
                res.getString(6),
                
                });
                //nomortabel++;
          }
            tabel.setModel(Tabelcoy);
          }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Data yang dicari tidak ada !!!!");
 
          }
         textcari.setText("");
    }//GEN-LAST:event_cariActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        menu_admin a = new menu_admin();
        a.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void cetak_semuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak_semuaActionPerformed
        try{
            JasperPrint print = JasperFillManager.fillReport("foto/capres/data_capres.jasper",new HashMap(),koneksi.GetConnection());
            JasperViewer.viewReport(print,false);
            bersih();
        }catch(JRException e){
          JOptionPane.showMessageDialog(null,"Gagal Membuat Laporan"+e,"Cetak Laporan",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
        Logger.getLogger(data_capres.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_cetak_semuaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          try{
            
            String b = id_capres.getText().toString();
            HashMap parameters = new HashMap();
            parameters.put("id_capres",b);
            JasperPrint print = JasperFillManager.fillReport("foto/capres/data_capres_parameter.jasper", parameters,koneksi.GetConnection());
            JasperViewer.viewReport(print,false);
            bersih();
        }catch(JRException ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        } catch (SQLException ex) {
        Logger.getLogger(data_capres.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_capres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_capres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_capres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_capres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_capres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton browser;
    private javax.swing.JButton cari;
    private javax.swing.JButton cetak_semua;
    private javax.swing.JButton edit;
    private javax.swing.JTextField foto;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id_capres;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jk;
    private javax.swing.JRadioButton laki_laki;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField nama_capres;
    private javax.swing.JComboBox<String> no_urut;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField textcari;
    // End of variables declaration//GEN-END:variables
}
