
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class hasil_suara extends javax.swing.JFrame {
    /**
     * Creates new form data_panitia
     */
    public hasil_suara() {
        initComponents();
        lihatdata();
        setLocationRelativeTo(null);
        setTitle("Data Hasil Suara");
    }
    public void lihatdata(){
         DefaultTableModel ea = new DefaultTableModel();
        ea.addColumn("No urut");
        ea.addColumn("Jumlah Suara");
        
        try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
            String sql = "Select * from hasil_suara";
            ResultSet res = perintah.executeQuery(sql);
            while(res.next()){
                ea.addRow(new Object []{
                    
                    res.getString("no_urut"),
                    res.getString("jumlah_suara"),
                    
                });
            }
            tabel.setModel(ea);
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, "Error"+err);
            
        }
        
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        cetak_semua = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        textcari = new javax.swing.JTextField();
        lihat = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new
            javax.swing.ImageIcon(getClass().getResource("/user.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1020, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText(" HASIL SUARA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 20));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 730, 180));

        cetak_semua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cetak_semua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        cetak_semua.setText("Cetak Semua");
        cetak_semua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak_semuaActionPerformed(evt);
            }
        });
        getContentPane().add(cetak_semua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 170, 140));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polos.png"))); // NOI18N
        jButton3.setText("Cetak Parameter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 190, 140));

        textcari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(textcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 530, -1));

        lihat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lihat.setText("Lihat Data");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        getContentPane().add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));

        cari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        

    }//GEN-LAST:event_tabelMouseClicked

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        lihatdata();
    }//GEN-LAST:event_lihatActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
                 DefaultTableModel Tabelcoy = new DefaultTableModel();
     Tabelcoy.addColumn("No urut");
     Tabelcoy.addColumn("Jumlah Suara");
     String cari = textcari.getText();
         try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
          String sql = "Select * From hasil_suara Where no_urut LIKE '%"+cari+"%'"
                    + "OR jumlah_suara LIKE '%"+cari+"%' ORDER BY no_urut";
            ResultSet res = perintah.executeQuery(sql);
          while(res.next()){
                Tabelcoy.addRow(new Object[]{
                res.getString(1),
                res.getString(2),
                
                });
                //nomortabel++;
          }
            tabel.setModel(Tabelcoy);
          }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Data yang dicari tidak ada !!!!");
 
          }
         textcari.setText("");
    }//GEN-LAST:event_cariActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       login_panitia a = new login_panitia();
        a.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void cetak_semuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak_semuaActionPerformed
         try{
            JasperPrint print = JasperFillManager.fillReport("foto/hasil_suara/data_hasil_suara.jasper",new HashMap(),koneksi.GetConnection());
            JasperViewer.viewReport(print,false);
           
        }catch(JRException e){
          JOptionPane.showMessageDialog(null,"Gagal Membuat Laporan"+e,"Cetak Laporan",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(hasil_suara.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cetak_semuaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          try{
              int table = tabel.getSelectedRow();
              
              String a = tabel.getValueAt(table,0).toString();
            
            HashMap parameters = new HashMap();
            parameters.put("no_urut",a);
            JasperPrint print = JasperFillManager.fillReport("foto/hasil_suara/data_hasil_suara_parameter.jasper", parameters,koneksi.GetConnection());
            JasperViewer.viewReport(print,false);      
        }catch(JRException ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        } catch (SQLException ex) {
            Logger.getLogger(hasil_suara.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasil_suara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasil_suara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasil_suara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasil_suara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasil_suara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JButton cetak_semua;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lihat;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField textcari;
    // End of variables declaration//GEN-END:variables
}
