/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form menu_admin
     */
    public menu_admin() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu Utama Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        data_panitia = new javax.swing.JButton();
        data_pemilih = new javax.swing.JButton();
        data_capres = new javax.swing.JButton();
        hasil_suara = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new
            javax.swing.ImageIcon(getClass().getResource("/user.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setText("SELAMAT DATANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        data_panitia.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        data_panitia.setText("DATA PANITIA");
        data_panitia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_panitiaActionPerformed(evt);
            }
        });
        getContentPane().add(data_panitia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 220, 50));

        data_pemilih.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        data_pemilih.setText("DATA PEMILIH");
        data_pemilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_pemilihActionPerformed(evt);
            }
        });
        getContentPane().add(data_pemilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 220, 50));

        data_capres.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        data_capres.setText("DATA CAPRES");
        data_capres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_capresActionPerformed(evt);
            }
        });
        getContentPane().add(data_capres, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 220, 50));

        hasil_suara.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        hasil_suara.setText("HASIL SUARA");
        hasil_suara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasil_suaraActionPerformed(evt);
            }
        });
        getContentPane().add(hasil_suara, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 220, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PaintSquares_1920x1234.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_panitiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_panitiaActionPerformed
        data_panitia a = new data_panitia();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_data_panitiaActionPerformed

    private void data_pemilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_pemilihActionPerformed
        data_pemilih a = new data_pemilih();
        a.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_data_pemilihActionPerformed

    private void data_capresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_capresActionPerformed
  data_capres a = new data_capres();
  a.setVisible(true);
  
  setVisible(false);
    }//GEN-LAST:event_data_capresActionPerformed

    private void hasil_suaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasil_suaraActionPerformed
        data_hasil_suara a = new data_hasil_suara();
        a.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_hasil_suaraActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        login_admin a = new login_admin();
        a.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton data_capres;
    private javax.swing.JButton data_panitia;
    private javax.swing.JButton data_pemilih;
    private javax.swing.JButton hasil_suara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
