
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class pencoblosan extends javax.swing.JFrame {

    /**
     * Creates new form pencoblosan
     */
    public pencoblosan() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pemilihan");
        combo_id_capres();
    }
    
    public void combo_id_capres(){
         id_capres.removeAllItems();
        
        try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
            String sql = "Select * from capres";
            ResultSet res = perintah.executeQuery(sql);
            while(res.next()){
                id_capres.addItem(res.getString("id_capres"));
            }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err);
     
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_capres = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        nama_capres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        no_urut = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new
            javax.swing.ImageIcon(getClass().getResource("/user.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("MASA DEPAN NEGARA DI TENTUKAN OLEH ANDA SEKARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("PILIH LAH PEMIMPIN DENGAN YAKIN DAN BIJAK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("NO URUT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        id_capres.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id_capres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        id_capres.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                id_capresItemStateChanged(evt);
            }
        });
        getContentPane().add(id_capres, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 270, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("NO URUT / ID CAPRES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        nama_capres.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(nama_capres, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 270, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("NAMA CAPRES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        no_urut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(no_urut, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 270, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("PILIH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 500, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_capresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_id_capresItemStateChanged
           try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
            String sql ="Select * from capres where id_capres = '"+id_capres.getSelectedItem()+"'";
            ResultSet res = perintah.executeQuery(sql);
            while(res.next()){
                nama_capres.setText(res.getString("nama_capres"));
                no_urut.setText(res.getString("no_urut"));
            }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err);
        }
    }//GEN-LAST:event_id_capresItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       int suara = 1;
        try{
            Statement perintah = (Statement) koneksi.GetConnection().createStatement();
            String sql = "Insert into pencoblosan (id_capres,no_urut,jumlah_suara) values ('"+id_capres.getSelectedItem()+"','"+no_urut.getText()+"','"+suara+"')";
            perintah.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "TERIMAKASIH TELAH MEMILIH");
            menu_utama a =new menu_utama();
            a.setVisible(true);
            setVisible(false);
             perintah.close();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        login_pemilih a= new login_pemilih();
        a.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pencoblosan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pencoblosan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pencoblosan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pencoblosan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pencoblosan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> id_capres;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nama_capres;
    private javax.swing.JTextField no_urut;
    // End of variables declaration//GEN-END:variables
}
